name: CI
run-name: >-
  ${{ github.event_name == 'pull_request' && format('CI: pull request checks') ||
      github.event_name == 'release' && format('CI: release {0}', github.ref_name) ||
      format('CI: branch merge checks') }}
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - main
  release:
    types:
      - edited
      - published
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: '1'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v5.3.0
        with:
          java-version: 17
          distribution: temurin
      - name: Restore cache
        uses: coursier/cache-action@v8.1.1
        id: coursier-cache
      - name: Run checks
        run: ./mill __.checkStyle + __.test + __.publishLocal
      - name: Publish artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
        run: ./mill mill.scalalib.SonatypeCentralPublishModule/
